# Mandatory include
include:
  - project: 'city-of-helsinki/kuva/ci-cd-config/ci-configuration'
    ref: v2
    file: '/.gitlab-ci-template.yml'
 
variables:
  APP_MIGRATE_COMMAND: /app/.prod/on_deploy.sh
 
# Build stage must be included and it must extend .build.
build:
  extends: .build
 
review:
  variables:
    K8S_SECRET_ALLOWED_HOSTS: "*"
    K8S_SECRET_DEBUG: 1
    POSTGRES_ENABLED: 1
    K8S_SECRET_SKIP_DATABASE_CHECK: 1

staging:
  only:
    refs:
      - master
  variables:
    K8S_SECRET_ALLOWED_HOSTS: "*"
    K8S_SECRET_SKIP_DATABASE_CHECK: 1

production:
  variables:
    K8S_SECRET_ALLOWED_HOSTS: "*"
    K8S_SECRET_SKIP_DATABASE_CHECK: 1    
