version: '3.7'
services:
    postgres:
        image: helsinkitest/postgis:9.6-2.5-alpine
        restart: on-failure
        environment:
            POSTGRES_USER: assignments
            POSTGRES_PASSWORD: assignments
            POSTGRES_DB: coding_assignments
        ports:
            - 5433:5432
        volumes:
          - pgdata:/var/lib/postgresql/data
        container_name: profile-db

    django:
        build:
            context: .
            target: production
        environment:
            DATABASE_URL:
              postgres://assignments:assignments@profile-db/coding_assignments
            DATABASE_HOST: "profile-db"
        volumes:
            - .:/app
            - django-media-volume:/var/media/
        ports:
            - "8080:8080"
        depends_on:
            - postgres
        container_name: profile-backend

volumes:
        pgdata:
            driver: local
        django-media-volume:


networks:
    default:
        name: helsinki

